CREATE TABLE COMMUNITY.PUBLIC."user" (
	ID INTEGER DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_25ACA873_FC31_41E6_94FC_E0FADE6CD89E" NOT NULL AUTO_INCREMENT,
	ACCOUNT_ID VARCHAR(100),
	NAME VARCHAR(50),
	TOKEN VARCHAR(36),
	GMT_CREATE BIGINT,
	GMT_MODIFIED BIGINT
);